
IF OBJECT_ID('dbo.A') IS NULL
    EXEC ('CREATE VIEW A AS SELECT N = 0');

GO

DECLARE @t NVARCHAR(100) = CONVERT(NVARCHAR(100), @@TRANCOUNT);
DECLARE @sql NVARCHAR(max) = 'ALTER VIEW A AS SELECT TRANCOUNT = ' + @t + ', X = 123';
EXEC (@sql)
